"""Initial schema

Revision ID: 37c5c3590ad9
Revises: 
Create Date: 2026-09-22 21:47:43.663073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c5c3590ad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('supplier_upi', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index(op.f('ix_inventory_sku_id'), 'inventory', ['sku_id'], unique=False)
    op.create_table('credit_offers',
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['inventory.sku_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_credit_offers_offer_id'), 'credit_offers', ['offer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('linked_sku_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['linked_sku_id'], ['inventory.sku_id'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_txn_id'), 'transactions', ['txn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_txn_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_credit_offers_offer_id'), table_name='credit_offers')
    op.drop_table('credit_offers')
    op.drop_index(op.f('ix_inventory_sku_id'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
